[package]
org = "wso2"
name = "list_products"
version = "0.1.0"
distribution = "2201.13.0"

[[dependency]]
org = "ballerinax"
name = "microsoft.dynamics365.scm"
version = "0.2.0"
repository = "local"
