[package]
org = "ballerinax"
name = "microsoft.dynamics365.scm"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Supply Chain Management", "Area/ERP & Business Operations", "Vendor/Microsoft", "Dynamics365", "SupplyChain", "ERP", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.scm"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"
export = ["microsoft.dynamics365.scm", "microsoft.dynamics365.scm.mock.server"]

[build-options]
observabilityIncluded=true
